label end1:
    "..."
    "I don't know what I'm doing any more."
    scene bg memory with Dissolve (0.5)
    "I had just left work when I saw it on the news."
    "It had been afternoon news, but I didn't have news apps on my phone any more so I hadn't found out. {w}Keeping up had gotten tiring, after awhile."
    "I watched, but the news broadcaster on the screen was inaudible. There was too much noise on the train."
    "I read the subtitles though; {w}another 500 words off the dictionary, including phrases. They didn't have a list."
    "Then again, a list of words that didn't exist would go against the point of their non-existence."
    "I felt strange, on that train. {w}I looked down at my hands. {w}I glanced at the other people."
    "Nobody seemed out of place."
    "I glanced at my own reflection in the glass, and behind it at the black subway walls hurtling past."
    "I didn't seem out of place either."
    "There was a fire extinguisher at the end of the carriage, and I had a sudden urge to pick it up and bash it against the windows until the windows broke."
    "I pictured clawing open the doors of the carriage and leaping into the dark. {w}Cracking all my bones open as I went from terminal velocity to the metal tracks below."
    "I wondered if someone would try to drag me back."
    "I thought: {w}I should call them."
    "And then I was checking my phone again, my finger ready to touch the call button. {w}But then I didn't know who I wanted to call."
    "I put the phone down. {i}I was briefly confused."
    "Then I looked up again, at the screen on the train wall. {w}The broadcaster had started talking about a combined services ceremony. A pixellated picture of a uniformed parade was next to her."
    "I thought: {w}I should call them, they would find this funny."
    "And when I checked my phone again, I went through my contacts list."
    "But nobody seemed right."
    "And when the train doors opened on my stop my hands were shaking on my phone. {w}Or rather the phone was shaking, because the train was shaking also."
    "Hadn't there been someone beside me? {w}And now they were gone."
    "There was no reason for the loss I felt."
    "Perhaps it was just an extension of the loss of sitting in a train carriage with two dozen other humans. {w}The awareness of a rest of humanity, proof of life close enough to touch, only no-one was touching."
    "I checked my phone again, went down to the end of my contacts list where all the numbers with disappeared names were."
    "A dozen of them, sitting together without description or owner. {w}The names had gone, but the numbers remained."
    "Sometimes the numbers didn't remain. It was fickle and arbitrary like that."
    "Before I got home, I called all twelve."
    "None of them were right, of course."
    "There was one woman who answered the phone, but she sounded old and shrill, and when I told her who I was she said—{w}{i}I don't know anyone with that name.{/i}"
    "After she hung up, I wondered if the person I wanted to call was her anyway."
    "I felt it wasn't. {w}Then I felt I could not trust myself."
    "I knew I had forgotten a lot, by now. That part was inevitable. {w}I knew I had probably forgotten more, only I forgot the forgetting too."
    "It was flimsy, the urgency that rose in me. {w}The kind of thing that stoked itself on hyperbole. {w}But I was in a mood for hyperbole."
    "That was how it worked. If I let go of the urgency, I would let go of the memory of urgency too."
    "So I ran. {w}So I ran back to my flat. {w}So I hauled the gate shut on the elevator and after a moment of standing in that empty square of space I opened my mouth."
    "It was sort of an animal thing, the sound that came out. {w}Like it had been in a place, in my throat, for some time already—and suddenly it was tearing itself out of itself."
    "I only did it—I only screamed—because there wasn't a security camera in the elevator. My building was just too old."
    "Anyone waiting for the elevator would have heard, though."
    "I felt a relief in that. I wanted to be heard, although I did not want to be recognised."
    scene bg room
    "..."
    "There it is now, that familiar sense of loss again."
    "It's in my chest, a little below the heart."
    "There's something I've forgotten, I'm sure. {w}{i}Someone{/i} I've forgotten."
    "But I can't help how the loss goes away too, finds itself and mends itself like a sped-up tape of a bone breaking and mending."
    "I'm tired of searching for the loss, scratching all the skin on my body to try and find the seam that hides the wound."
    "This room is covered all over with the debris of how hard I try. {w}But it always goes away."
    "Names, dates, faces, events. {w}One of these days I'll open my notebook and it'll be empty. {w}Just white space, ready to be written in all over again."
    "Maybe that's already happened, I wouldn't even know."
    p "..."
    p "I'm tired, that's all."
    "Maybe tomorrow, I'll feel this loss again. Maybe tomorrow, I'll feel it and try to remember."
    "Maybe it'll be another me who isn't really me."
    "I don't think I'm really myself these days, either."
    p "..."
    p "I don't want to think about this right now."
    "I rub my brow and look down at my feet. {w}I haven't taken my shoes off yet."
    p "..."
    "Well, my keys are still on the table, and I've only eaten lunch today. {w}I think I'll go downstairs and get something to eat, something cheap."
    "Maybe curry from the closest noodle place."
    "I don't look behind me as I leave."
    "..."
    #play sound click
    window hide
    scene bg black with Dissolve (0.5)
    scene ending1 with Dissolve (0.5):
        size (1920,1080)
    pause
    $ persistent.end1 = True
    return

label end2:
    scene bg room
    "..."
    "I'm starting to remember more now."
    "...Who knew memory could be so tiring."
    "I sit down and turn to a different page in the open notebook. I take out a pen."
    "I think back to..."
    scene bg memory
    "That new year, we had been by the pier."
    "I'd bought a cold lunchbox from the Japanese supermarket. {w}He had a couple of oranges."
    "We sat on a bench, right by the sea."
    a "You ever think of going home?"
    p "Home?"
    a "Yeah, man, I kept thinking about it this morning. Going home and all that shebang. {w}I was checking my phone, waiting for that call."
    p "..."
    a "Waiting for my sister to call me. {w}Or my mum. {w}Thought they'd beg me to go home, just for an evening, just to eat with them."
    p "And they didn't?"
    a "Yeah, got nothing. No skin off my back, I guess."
    a "I'm still here with you, eh? We're celebrating just fine."
    p "Their loss."
    a "Exactly."
    p "..."
    p "It's pretty cold today."
    a "Oh yeah, for sure, cold enough to freeze the tits off a dolphin."
    a "You think dolphins have tits?"
    p "I've never seen one. Probably?"
    a "Probably."
    "We lapsed into silence."
    p "I think the last time I went back was after my old man offed himself."
    a "Oh, wow, man. That heavy?"
    p "Not that heavy, I didn't really mind. {w}He was kinda a piece of shit anyway, no loss."
    a "Hey, I'll drink to that! No loss to the world, and fuck that guy."
    p "...Didn't seem like home though, when I went back."
    p "Didn't seem like anything. {w}Just a house. {w}Not even my house."
    p "And I thought that was it. I'd been thinking about that house for so long, but then it didn't feel like anything. {w}So I really thought that was it."
    a "And...I'm guessing it wasn't?"
    p "Yeah. I still think about going home."
    p "But it's not like I can. {w}It's not like—somehow—{w}the place is there, like, the place is there but that isn't my home."
    p "And I want to go home but my home is gone."
    p "It's nowhere. {w}The home I want to go back to is nowhere."
    p "..."
    a "..."
    a "You ever think about leaving this place then?"
    p "What?"
    a "Leaving. Finding somewhere new."
    a "Cause I'm thinking about it these days, leaving the city. {w}Leaving all this...shit behind."
    p "Going abroad?"
    a "Yeah. Like...you know, I don't think you were quite right with that 'nowhere' stuff."
    a "Think about this way. You {i}do{/i} know where your home is."
    p "I don't, I just...I thought I did, and I was wrong."
    a "Nah, you do. Because you know what it looks like, and it looks like your house but from ages ago, from when you were a kid or something."
    a "From some kinda time when it {i}was{/i} home."
    p "...I guess, man."
    a "C'mon, look at me and tell me I'm wrong. I think—{w}when you went back to your old man's place—{w}I think you were at the right place, you just couldn't get back to the right time."
    p "..."
    p "...Isn't that worse?"
    a "Depends on your point of view. {w}But at least you know, right? You know that place exists."
    p "Existed."
    a "It still exists. {w}It's still in your memory, so it still exists."
    a "...That's why I'm thinking about leaving."
    p "You're afraid you'll forget?"
    a "Yeah. It keeps, I keep...{w}If staying here means forgetting, I'd rather go."
    p "..."
    a "You could come as well."
    p "I'm not like you."
    a "I know, man."
    a "...I know."
    scene bg room
    "...Right. {w}That's right."
    "Axel's gone."
    "He left."
    p "...That means at least he won't forget me, right?"
    p "Even if I..."
    "I don't know how long I sit on the plastic stool, looking at the ink on the page bleed. {w}At some point, {w}like a flutter of wings, {w}the words begin peeling away."
    "I just watch them go."
    "When I look up again, the room is darker. {w}The sun has set."
    "I stand, leaving the notebook behind, and go to the window."
    "They've been doing construction work down the street, so I haven't opened the window for a week now. {w}It's grimy, the glass caked over with dust."
    "I have to drag the metal latch to get it open."
    p "Ah..."
    #play sound cityscape
    "Now I can smell the city. {w}Smoke, metal, gas. {w}Someone in a neighbouring apartment cooking. {w}They're making something with tomatoes."
    "The air conditioning unit gets in the way, but I push the window out further."
    "It's night now, properly, but my vision is still full with light. {w}It leaks out of shuttered apartment windows, it spills onto the streets."
    "From every window that seeps light, there's a room with someone inside it. {w}Someone, a human."
    "It's hard to picture. {w}All those lives. All those thoughts."
    "There are people downstairs, I see them laughing."
    p "Is this how people live, without a past?"
    p "..."
    p "I have a sense that...{w}on the day I've forgotten everything, I'll finally be able to look at the world and see how beautiful it is."
    p "I'll see it all for the first time. {w}The city, the people, the clouds in the sky. {w}I'll see it all without loss."
    p "Won't that be wonderful?"
    p "..."
    window hide
    scene bg black with Dissolve (0.5)
    scene ending2 with Dissolve (0.5):
        size (1920,1080)
    pause
    $ persistent.end2 = True
    return

label end3:
    scene bg room
    "I take a closer look at the clock."
    p "Maybe..."
    "..."
    "It's dead, so I might as well replace the battery."
    "I have to reach to grab it. {w}It doesn't come easy either."
    #play sound clatter
    p "There we go."
    "There's dust on top of the clock, a thick amount. {w}My fingers come away almost black."
    "And when I turn it over..."
    "There's a bunch of numbers hacked into the back of the plastic."
    p "..."
    p "Carving with a scalpel, huh."
    "Is this it? {w}It's worth a try."
    "If the clock's been sitting there for all this time, the numbers probably won't go away if I let my eyes stray off it."
    "But I grip the clock tight as I go to pick up my phone. {w}I keep two fingers pressed over the gouged plastic."
    "My phone is still sitting by the keys on the table. I pick it up with one hand, dialling in the numbers on the back of the clock."
    "My fingers are nerveless. The number isn't a local number."
    #play sound phonecall
    "..."
    "I'll laugh if this call goes into his voicemail inbox."
    "If this is even him."
    #play sound phoneclick
    m "Hello?"
    "There's noise in the background of the call. Static as well, the connection isn't very good."
    "But now that I hear it, I recognise this voice."
    p "Axel?"
    a "Yes—{w}listen, can I call you back in a—"
    p "No!"
    "My own voice is loud in my ears."
    p "Don't call me back, stay on the line. Just—{w}stay on the fucking line."
    a "...Loy?—{w}Wait, is that you? Loy?"
    p "...Yeah. Yeah. It's me. {w}So just don't hang up."
    p "Please."
    "I wait. {w}For a moment, there's no reply on the other end. And then..."
    a "Yeah...I...Yes, sure. Of course. Don't worry, I won't hang up—{w}but—{w}I have to do something for a sec. You stay on the line too, yeah?"
    "I can't discern his tone of voice, not with all the static. He sounds different, though I can't tell how. {w}Maybe I just don't remember what he's meant to sound like."
    "There's more noise in the backdrop. Voices. They come and go."
    "I notice I've started leaning against the door. Maybe because I can't feel much of my body, suddenly."
    "So I slide down until I'm sitting, my back against the rail."
    "Eventually, Axel's voice comes back."
    a "Loy, hello? You still there?"
    p "I'm here."
    a "Oh, great! "
    "I think he sounds relieved."
    a "I, uh, I don't know what to say, really. I mean...I'm lost for words?"
    "He laughs in a crackle of static."
    a "Well, how are you?"
    p "..."
    p "I'm fine."
    p "...I forgot you."
    a "Yeah, I mean...{w}I did figure that out I guess. {w}This is the first time you've called me in, heck, in awhile."
    a "Uh—don't take that the wrong way. I'm really happy right now, I'm glad you called."
    p "...Right."
    a "So you're...{w}Where are you now, Loy?"
    "..."
    l "...I'm still here."
    a "In that city?"
    l "Yeah."
    a "I see, I see. Hah, somehow I thought you might've left as well."
    l "No. I'm still here."
    "I turn over my palm, the tips of my fingers nearly black with dust."
    "I don't understand."
    "Or I think I might understand, I might be starting to. But I'm not really interested in understanding. {w}But for some reason, I still open my mouth."
    l "Did I call you before?"
    a "Yeah. I think the last time was, uh—{w}don't make me look like I've memorised this—{w}January two years ago?"
    l "Oh."
    "Somewhat dully, I roll that over my mind."
    l "Two years ago, huh."
    a "Yeah."
    "He fumbles over a couple of other words, but I can't really hear them through the bad connection."
    "I rub my fingertips over the knee of my trousers."
    l "You could have called me."
    a "..."
    "There's silence on the other end of the line. {w}When Axel laughs, it's one of his short and sharp laughs, the kind that doesn't mean its own sound."
    a "I did. You didn't..."
    l "I didn't recognise you?"
    "His silence is pretty damning."
    a "I did keep calling. But you changed numbers or something, last year, and then I couldn't..."
    l "Oh. Yeah, I got into trouble because my phone card was an old, hadn't registered it to my name. {w}I had to get a new number."
    a "Right."
    "The room is stifling."
    "Years?"
    "It's been years?"
    "But then—That can't be—"
    scene bg black with Dissolve (0.1)
    with flash
    scene bg room with Dissolve (0.1)
    with flash
    a "Breathe, my guy, breathe. Take it slow, yeah? {w}Inhale, now hold it for one, {w=0.3}two, {w=0.3}three..."
    "I breathe."
    "After awhile, I can almost feel my own body again."
    a "...You okay over there? Do you need anything?"
    l "I need..."
    "I stop to think about it."
    l "I need to get out of here. Out of this apartment."
    a "That sounds like a great idea, Loy. Do you have your shoes on?"
    "I look down at my feet."
    l "Yeah, I didn't take them off."
    a "Great, okay. Then I think that's—{w}Wait, shit, remember your coat."
    "Moving to leave the room, I stop with my hand over the metal handle of the door. The keys in my fist jangle."
    "{i}Oh,{/i} I think."
    l "It'll just be the same."
    "Inside and outside. {w}Still in the guts of a city clawing out its own past to be clean."
    l "Like those Russian dolls, you know the ones. Cracking open one shell and you're just inside the next, so it turns out you haven't broken out after all."
    a "Listen, I think you should get some fresh air anyway."
    l "...Yeah. You're right."
    l "Don't hang up."
    a "I won't."
    a "Loy."
    l "Yeah?"
    "For a moment, there's silence."
    a "You know I still send you postcards."
    l "Oh."
    "Then—I wonder if..."
    "I glance at the corkboard, but it's already leaving my sight. {w}I shut the front door."
    "I feel a little terrible, I think."
    "There's only so long my phone will last without charging. {w}There's only so long either of us can go without sleep, without the accidental push of a button that would cut off our call."
    "Maybe I'll wake up tomorrow and this will be gone again."
    "At least there's the now. {w}Maybe that's what all the posters meant with the stuff about grasping the present."
    "I reach the end of the hallway, and push at the rusted elevator control panel. After a moment, I decide to take the stairs instead."
    l "Hey, you still there?"
    a "I'm still here."
    "In some part of my chest, something is still constricted. {w}It still feels like I can't breathe."
    "Or maybe it feels like I'm taking a breath for the first time, after years of not-breathing and forgetting how."
    l "I guess it could be either."
    a "Hm?"
    l "Just don't hang up."
    a "I won't. {w}In that case, I guess we should talk a bit more...you wanna hear about this how this one tennis champion punched the living daylights out of this other tennis champion last week?"
    l "...Sure. Who am I rooting for?"
    a "Great question, great question. So I like both, but..."
    "..."
    "..."
    window hide
    scene bg black with Dissolve (0.5)
    scene ending3 with Dissolve (0.5):
        size (1920,1080)
    pause
    $ persistent.end3 = True
    return
